### ISSUE TITLE
Real CRJ has no auto-thrust, AP speed button is wrong

### ISSUE THREAD

**Issue by d-jsb** [d-jsb/CRJ700-family#23]
Thrust must be set manually.
Real CRJ autopilot: "speed" is a vertical mode, e.g. you give a desired airspeed and the AP tries to match it by pitching nose up or down (maybe impossible dep. on thrust and other parameters)

**Comment by Ravenslofty** [comment]
It appears that this has been solved in the new autopilot system, so this should probably be closed.

**Comment by d-jsb** [comment]
Only half of it. Auto thrust is removed, but speed mode is not yet rewritten

**Comment by d-jsb** [comment]
Auto thrust function is re-enabled as a convenience option (config menu).
