### ISSUE TITLE
IDG (AC generators) may fail in flight

### ISSUE THREAD

**Issue by d-jsb** [d-jsb/CRJ700-family#25]
Engine idle N2 may drop below limit for stable AC output -> AC low / fail
Need to check engine/IDG parameters

**Comment by d-jsb** [comment]
reduced N2 limit for generator

**Comment by ghost** [comment]
Still present or regression. Needs testing.

**Comment by d-jsb** [comment]
Fixed. Voltage will not depend on engine rpm once engine is running.
