### ISSUE TITLE
Emergency hydraulic circuits don't work when in AUTO mode

### ISSUE THREAD

**Issue by ghost** [d-jsb/CRJ700-family#43]
When out of fuel or with both engines out, emergency hydraulics won't work if switches for those circuits are set to AUTO instead of ON. Is this the real behaviour? Should they be set to ON by default instead of AUTO as described in checklists?

**Comment by ghost** [comment]
Does this help?

"
Hydrolic pumps to AUTO provides 

pumps 1B and 2B to operate when
• respective bus is powered
• any generator is operating
• flaps not at zero (0)   "

"
The ADG Bus powers...   

• Flaps & Slats at 1/2 speed
• Pitch trip
• Hydraulic pump 3B
• A/C Essential Bus  
ADG powers hydraulic pump _____ regardless of switch position   

3B"

**Comment by d-jsb** [comment]
From the FOM:
"System 3 main pump (3A) normally runs continuously, while the backup pump (3B) is available during periods of high flow requirments. Pump 3B is automatically powered, during an AC power failure, by the air driven generator (ADG) when it is deployed."

"AC motor pumps 1B and 2B do not automatically start during
or after an engine failure."

"Hydraulic system No. 3 AC motor pumps (ACMPs) are controlled by switches on the
hydraulic control panel. ACMP 3A runs continuously to maintain normal system
pressure. ACMP 3B operates during takeoffs and landings (based on Flaps setting >0). 
The ADG bus automatically powers ACMP 3B when the ADG is deployed (independent of the flight
compartment 3B switch setting)."
