### ISSUE TITLE
Implement canvas nav display on MFD

### ISSUE THREAD

**Issue by ghost** [d-jsb/CRJ700-family#50]
adapt Airbus/othercompany nav display for use in CRJ.

**Comment by Umoxfo** [comment]
I have developed canvas nav display,  but it is not working page title, way point information, etc.

https://github.com/Umoxfo/CRJ700-family.git

**Comment by d-jsb** [comment]
Nice work :) What are your further plans regarding canvas?

**Comment by Umoxfo** [comment]
I try to develop canvas EICAS display.

**Comment by d-jsb** [comment]
Ok, maybe we should coordinate our efforts on this :) Unfortunately it happens quite often that people work on the same project without knowing of each other so I created a threat in the forum where we can talk and share our ideas: https://forum.flightgear.org/viewtopic.php?f=4&t=31088
I collected many little pieces of documentation and pictures on CRJ700/900 that might be helpfull.
