### ISSUE TITLE
Aircraft moves on ground when parked.

### ISSUE THREAD

**Issue by ghost** [d-jsb/CRJ700-family#56]
even with parking brake applied

**Comment by d-jsb** [comment]
Adding a parking break to nose gear in FDM does not fix the issue. Should be addressed via forum to community.

**Comment by d-jsb** [comment]
Seems to be a general FG problem, other aircrafts show same problem: Citation-X, MD-81

**Comment by d-jsb** [comment]
Known problem with yasim: http://buckarooshangar.com/flightgear/yasimtut_landinggear.html (bottom)
