### ISSUE TITLE
Engines keep original model skin

### ISSUE THREAD

**Issue by fjpr** [d-jsb/CRJ700-family#64]
OS Kubuntu 16.10 Flightgear V2016.2.1

![bombardier crj 1000](https://cloud.githubusercontent.com/assets/5462467/16969693/0e7f1682-4e17-11e6-80db-77175ec17013.png)

**Comment by d-jsb** [comment]
Confirmed. Happens only when rembrandt is enabled.

**Comment by d-jsb** [comment]
Fixed by removing alpha channel from blank liveries
