### ISSUE TITLE
Livery list doesn't appear

### ISSUE THREAD

**Issue by MysticalLlama** [d-jsb/CRJ700-family#65]
Whenever I click the 'Select Livery' button in the hotbar, the typical livery list doesn't get pulled up. I have tried it on the 700 and 700ER.

**Comment by d-jsb** [comment]
Please add OS, version of FG and version of CRJ (see CRJ*-set.xml) to your report

**Comment by MysticalLlama** [comment]
OS: OS X Yosemite Version 10.10.5, FG: 2016.2.1, CRJ: CRJ700 1.5.2

**Comment by d-jsb** [comment]
Please try again with the latest version of CRJ700 family

**Comment by d-jsb** [comment]
Could not reproduce.
